# Generated by Django 3.2.3 on 2023-12-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='recipe/image', verbose_name='Изображение'),
        ),
    ]
