# Generated by Django 3.2.3 on 2023-12-28 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_rename_tag_recipe_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredients',
            old_name='unit_of_measurement',
            new_name='measurement_unit',
        ),
    ]
